services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: ghcr.io/geminianuj77-ship-it/employee-management-system:${IMAGE_TAG}
    container_name: ems-container

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
